[config]
_sender = ['credit454ec43994@qifudigitech.com', 'CREDIT371b6c5c29@qifudigitech.com', 'CREDIT71b19e4f38@qifudigitech.com',
    'CREDIT68ed060833@qifudigitech.com', 'CREDITb2bdb81637@qifudigitech.com', 'CREDIT39159b4d83@qifudigitech.com',
    'CREDITca91b5a336@qifudigitech.com', 'CREDIT52f53f9c03@qifudigitech.com','CREDIT3a14e93789@qifudigitech.com',
    'CREDIT6f6d01c553@qifudigitech.com','CREDITb7d9328468@qifudigitech.com']
_to = ['CREDITff4b7db561@qifudigitech.com']
email_url = 'https://p88528v.hulk.bjzdd.qihoo.net/mail/'
email_pass = '{9N3aC2AZs'